import React from 'react';
import { DataSourceType, SeverityLevel, IncidentStatus } from '../../shared/types';

interface BadgeProps {
  children?: React.ReactNode;
  variant?: 'measured' | 'simulated' | 'severity' | 'status' | 'neutral' | 'success' | 'warning' | 'danger';
  severity?: SeverityLevel;
  status?: IncidentStatus;
  size?: 'xs' | 'sm' | 'md';
  pulse?: boolean;
  className?: string;
}

export const Badge: React.FC<BadgeProps> = ({
  children,
  variant = 'neutral',
  severity,
  status,
  size = 'sm',
  pulse = false,
  className = '',
}) => {
  const sizeClasses = {
    xs: 'px-1.5 py-0.5 text-[10px] gap-1',
    sm: 'px-2 py-0.5 text-[11px] gap-1.5',
    md: 'px-2.5 py-1 text-xs gap-1.5',
  }[size];

  // Specific handling for Measured vs Simulated
  if (variant === 'measured' || children === DataSourceType.MEASURED) {
    return (
      <span
        className={`inline-flex items-center font-medium font-mono rounded-full bg-emerald-500/10 text-emerald-700 dark:text-emerald-400 border border-emerald-500/25 ${sizeClasses} ${className}`}
        title="Real telemetry from user browser or hardware probe"
      >
        <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
        {children || 'Measured'}
      </span>
    );
  }

  if (variant === 'simulated' || children === DataSourceType.SIMULATED) {
    return (
      <span
        className={`inline-flex items-center font-medium font-mono rounded-full bg-amber-500/10 text-amber-700 dark:text-amber-400 border border-amber-500/25 ${sizeClasses} ${className}`}
        title="Synthetic telemetry generated by simulation engine"
      >
        <span className="w-1.5 h-1.5 rounded-full bg-amber-500" />
        {children || 'Simulated'}
      </span>
    );
  }

  // Severity variants
  if (severity) {
    const severityStyles = {
      [SeverityLevel.CRITICAL]: 'bg-rose-500/10 text-rose-700 dark:text-rose-400 border-rose-500/25',
      [SeverityLevel.HIGH]: 'bg-orange-500/10 text-orange-700 dark:text-orange-400 border-orange-500/25',
      [SeverityLevel.MEDIUM]: 'bg-amber-500/10 text-amber-700 dark:text-amber-400 border-amber-500/25',
      [SeverityLevel.LOW]: 'bg-blue-500/10 text-blue-700 dark:text-blue-400 border-blue-500/25',
      [SeverityLevel.INFO]: 'bg-slate-500/10 text-slate-700 dark:text-slate-400 border-slate-500/25',
    }[severity];

    return (
      <span
        className={`inline-flex items-center font-semibold font-mono rounded-full border ${severityStyles} ${sizeClasses} ${className}`}
      >
        {pulse && <span className="w-1.5 h-1.5 rounded-full bg-current animate-ping" />}
        {children || severity}
      </span>
    );
  }

  // Incident status variants
  if (status) {
    const statusStyles = {
      [IncidentStatus.REPORTED]: 'bg-amber-500/10 text-amber-700 dark:text-amber-400 border-amber-500/25',
      [IncidentStatus.ASSIGNED]: 'bg-blue-500/10 text-blue-700 dark:text-blue-400 border-blue-500/25',
      [IncidentStatus.INVESTIGATING]: 'bg-purple-500/10 text-purple-700 dark:text-purple-400 border-purple-500/25',
      [IncidentStatus.RESOLVED]: 'bg-emerald-500/10 text-emerald-700 dark:text-emerald-400 border-emerald-500/25',
      [IncidentStatus.CLOSED]: 'bg-slate-500/10 text-slate-600 dark:text-slate-400 border-slate-500/25',
    }[status];

    return (
      <span
        className={`inline-flex items-center font-medium rounded-full border ${statusStyles} ${sizeClasses} ${className}`}
      >
        {children || status}
      </span>
    );
  }

  const genericStyles: Record<string, string> = {
    neutral: 'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300 border-slate-200 dark:border-slate-700',
    success: 'bg-emerald-500/10 text-emerald-700 dark:text-emerald-400 border-emerald-500/25',
    warning: 'bg-amber-500/10 text-amber-700 dark:text-amber-400 border-amber-500/25',
    danger: 'bg-rose-500/10 text-rose-700 dark:text-rose-400 border-rose-500/25',
  };
  const activeStyle = genericStyles[variant] || genericStyles.neutral;

  return (
    <span className={`inline-flex items-center font-medium rounded-full border ${activeStyle} ${sizeClasses} ${className}`}>
      {pulse && <span className="w-1.5 h-1.5 rounded-full bg-current animate-ping" />}
      {children}
    </span>
  );
};
